services:
  pipeline_etl:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/google_credentials.json
    volumes:
      - .:/home/appuser/app
      - ./secrets/credentials.json:/app/secrets/google_credentials.json:ro
